# Generated by Django 2.0.3 on 2019-01-10 10:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('items', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='items_table',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('p_id', models.CharField(default='p1', max_length=20)),
                ('name', models.CharField(max_length=20)),
                ('price', models.IntegerField()),
                ('category', models.CharField(choices=[('Electronics', 'Electronics'), ('Fashion', 'Fashion'), ('Home', 'Home and Furniture'), ('TV', 'TV and Appliances'), ('Beauty and Personal Care', 'Beauty and Personal Care'), ('Sports', 'Sports')], max_length=20)),
                ('img', models.FileField(default='img', upload_to='')),
                ('feature', models.BooleanField(default=False)),
                ('discount', models.CharField(default=None, max_length=20)),
                ('discountprice', models.CharField(max_length=20)),
            ],
        ),
    ]
