# Generated by Django 2.0.3 on 2019-01-12 06:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('items', '0002_items_table'),
    ]

    operations = [
        migrations.CreateModel(
            name='CartTable',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uid', models.IntegerField()),
                ('itemid', models.IntegerField()),
                ('itemprice', models.IntegerField()),
                ('quantity', models.IntegerField()),
            ],
        ),
    ]
