# Generated by Django 2.0.3 on 2019-01-30 18:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('items', '0003_carttable'),
    ]

    operations = [
        migrations.AlterField(
            model_name='items_table',
            name='category',
            field=models.CharField(choices=[('Cameras', 'Cameras and Photos'), ('Computers', 'Computers and Laptops'), ('Home', 'Home and Furniture'), ('Smartphones', 'Smartphones and Tablets'), ('TV and Audio', 'TV and Audio'), ('Video Games and Console', 'Video Games and Console')], max_length=20),
        ),
    ]
