# Generated by Django 2.0.3 on 2019-01-30 18:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('items', '0005_auto_20190130_2350'),
    ]

    operations = [
        migrations.AlterField(
            model_name='items_table',
            name='category',
            field=models.CharField(choices=[('Cameras', 'Cameras and Photos'), ('Computers', 'Computers and Laptops'), ('Accessories', 'Accessories'), ('Smartphones', 'Smartphones and Tablets'), ('TV and Audio', 'TV and Audio'), ('Video Games and Console', 'Video Games and Console')], max_length=30),
        ),
    ]
