# Generated by Django 2.0.3 on 2019-02-05 09:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('items', '0007_categorytable'),
    ]

    operations = [
        migrations.AlterField(
            model_name='items_table',
            name='category',
            field=models.CharField(choices=[('Cameras and Photos', 'Cameras and Photos'), ('Computers  and Laptops', 'Computers and Laptops'), ('Accessories', 'Accessories'), ('Smartphones and Tablets', 'Smartphones and Tablets'), ('TV and Audio', 'TV and Audio'), ('Video Games and Console', 'Video Games and Console')], max_length=30),
        ),
    ]
