# Generated by Django 2.0.3 on 2019-02-10 19:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('items', '0011_auto_20190211_0124'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cart',
            name='items',
            field=models.ManyToManyField(blank=True, to='items.items_table'),
        ),
    ]
